body:
  - type: input
    attributes:
      name: host
      label: Pear Desktop API Server Host
      defaultValue: "127.0.0.1"
  - type: input
    attributes:
      name: port
      label: Pear Desktop API Server Port
      defaultValue: "26538"
